add_newline = false
# Move all information on right prompt
format = """$character"""
right_format = """$all"""

[line_break]
disabled = true

[character]
success_symbol = "[❯](white)[❯](green)[❯](bold green)"
error_symbol = "[❯](white)[❯](red)[❯](bold red)"
vicmd_symbol = "[❮](white)[❮](blue)[❮](bold blue)"

[cmd_duration]
min_time = 1000
format = "*[$duration](bold yellow)*"

# Somehow cloud ⛅ emoji breaks prompt so excludes cloud related prompts
[aws]
disabled = true
[gcloud]
disabled = true

[git_branch]
style = "bold blue"
format = "[$symbol$branch]($style) "

[git_status]
style = "bold green"
format = '([$all_status $ahead_behind]($style))'

conflicted = "🏳"
ahead = "[→](bold red)"
behind = "[←](bold red)"
diverged = "😵"
up_to_date = ""

untracked = "[?](bold yellow)"
stashed = ""
modified = "[*](bold red)"
staged = '[+\($count\)](green)'
renamed = "[*](bold red)"
deleted = "[*](bold red)"

[python]
disabled = true

[package]
disabled = true

[directory]
fish_style_pwd_dir_length = 1

[nodejs]
disabled = true
