(define custom-activate-default-im-name? #t)
(define custom-preserved-default-im-name 'google-cgiapi-jp)
(define default-im-name 'google-cgiapi-jp)
(define enabled-im-list '(google-cgiapi-jp))
(define enable-im-switch? #f)
(define switch-im-key '("<Control> "))
(define switch-im-key? (make-key-predicate '("<Control> ")))
(define switch-im-skip-direct-im? #f)
(define enable-im-toggle? #f)
(define toggle-im-key '("<Control> "))
(define toggle-im-key? (make-key-predicate '("<Control> ")))
(define toggle-im-alt-im 'direct)
(define uim-color 'uim-color-uim)
(define candidate-window-style 'vertical)
(define candidate-window-position 'caret)
(define enable-lazy-loading? #t)
(define bridge-show-input-state? #f)
(define bridge-show-with? 'time)
(define bridge-show-input-state-time-length 3)
